resources:
  - name: self_repo3
    type: GitRepo
    configuration:
      gitProvider: testIntAkhil
      path: akhilesh073/pipelinesAkhil
      branches:
        include: ^tests$

pipelines:
  - name: simplePipelines_to_upload_step
    steps:
      - name: Normal_Step
        type: Bash
        configuration:
          inputResources:
            - name: self_repo3
        execution:
          onExecute:
            - pushd "$res_self_repo3_resourcePath/"
            - save_tests saveTests/failing
            - echo "Passed"
            - popd
